version: "2"
checks:
  argument-count:
    config:
      threshold: 8
  complex-logic:
    config:
      threshold: 8
  file-lines:
    config:
      threshold: 2000
  method-complexity:
    config:
      threshold: 30
  method-count:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    config:
      threshold: 8
  return-statements:
    config:
      threshold: 8
  similar-code:
    enabled: false
  identical-code:
    enabled: false