version: "2"
plugins:
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
        - python
        - php
  eslint:
    enabled: true
    channel: __ESLINT_CHANNEL__
  fixme:
    enabled: true
  rubocop:
    enabled: true
exclude_patterns:
  - config/
  - db/
  - dist/
  - features/
  - "**/node_modules/"
  - script/
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - Tests/
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "**/*.min.js"
  - "**/*.min.css"
  - "**/__tests__/"
  - "**/__mocks__/"
checks:
  argument-count:
    config:
      threshold: 8
  complex-logic:
    config:
      threshold: 8
  file-lines:
    config:
      threshold: 2000
  method-complexity:
    config:
      threshold: 30
  method-count:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    config:
      threshold: 8
  return-statements:
    config:
      threshold: 16
  similar-code:
    enabled: false
  identical-code:
    enabled: false