version: "2"
checks:
  argument-count:
    config:
      threshold: 8
  complex-logic:
    config:
      threshold: 8
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 75
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4